import os
import streamlit as st
from google import genai

st.set_page_config(
    page_title="Prof. Eagan's Grading Assist Tool",
    page_icon="📝",
    layout="wide"
)

st.title("📝 Prof. Eagan's Grading Assist Tool")
st.caption("Exam Question Evaluator • McGraw-Hill Connect (20 Points)")

# Retrieve API Key from Streamlit Secrets or sidebar
api_key = os.environ.get("GEMINI_API_KEY")
if not api_key:
    api_key = st.sidebar.text_input("Enter Gemini API Key", type="password")

if not api_key:
    st.info("Please configure GEMINI_API_KEY in Streamlit Secrets or enter it in the sidebar to proceed.", icon="🔑")
    st.stop()

client = genai.Client(api_key=api_key)

col1, col2 = st.columns(2)

with col1:
    st.subheader("1. Question Prompt")
    question_prompt = st.text_area(
        "Paste algorithmic question prompt from Connect:",
        height=140,
        placeholder="A.J. is a cash-basis taxpayer owing $24,000..."
    )

    st.subheader("2. Connect Master Solution")
    connect_solution = st.text_area(
        "Paste synthesized solution generated by Connect:",
        height=160,
        placeholder="If A.J. pays the $24,000 in December..."
    )

with col2:
    st.subheader("3. Student Submission")
    student_submission = st.text_area(
        "Paste student response (do NOT include student name or ID):",
        height=360,
        placeholder="This year: 24,000 * 0.24 = 5,760 savings..."
    )

evaluate_btn = st.button("Evaluate Submission", type="primary", use_container_width=True)

if evaluate_btn:
    if not (question_prompt.strip() and connect_solution.strip() and student_submission.strip()):
        st.warning("Please populate all three fields before grading.", icon="⚠️")
    else:
        with st.spinner("Analyzing submission against Connect solution and rubric..."):
            prompt = f"""
You are an expert tax accounting teaching assistant evaluating student submissions for Prof. Eagan.

TASK:
Grade the student submission out of 20 points by comparing it against the provided Connect Synthesized Solution.

GRADING RUBRIC & POINT DEDUCTIONS (20 Points Total):
1. Current Year Tax Savings (4 pts): Correct nominal formula and result.
2. Next Year Nominal Tax Savings (4 pts): Correct nominal formula and result.
3. Present Value Application (5 pts): Correct discount factor selected and correctly applied to next year's savings.
4. Net Difference / Incremental Savings (3 pts): Correct net present value advantage calculated.
5. Recommendation & Rationale (4 pts): Clear timing choice and justification based on marginal rate versus time value of money.

SPECIAL INSTRUCTIONS:
- Carry-Through Errors: If the student makes an arithmetic error in an early step, penalize that line item once. Do NOT penalize downstream steps if they applied the correct logic/formula to their erroneous intermediate figure.
- Accept reasonable rounding (e.g., within a dollar or two due to rounding intermediates).
- Keep feedback constructive, encouraging, and clear.

INPUTS:
[QUESTION PROMPT]
{question_prompt}

[CONNECT MASTER SOLUTION]
{connect_solution}

[STUDENT SUBMISSION]
{student_submission}

OUTPUT FORMAT EXACTLY AS FOLLOWS:
SCORE: [X] / 20

RUBRIC BREAKDOWN:
- Current Year Savings: [X]/4 - [Brief explanation or 'Full credit']
- Next Year Nominal Savings: [X]/4 - [Brief explanation or 'Full credit']
- Present Value Calculation: [X]/5 - [Brief explanation or 'Full credit']
- Incremental Savings: [X]/3 - [Brief explanation or 'Full credit']
- Recommendation & Rationale: [X]/4 - [Brief explanation or 'Full credit']

CONNECT FEEDBACK:
[Write 2 to 4 concise sentences directly addressed to the student explaining what was correct, where deductions occurred, and summarizing the correct figures. This text will be pasted directly into Connect.]
"""
            try:
                response = client.models.generate_content(
                    model="gemini-2.5-flash",
                    contents=prompt,
                )
                output = response.text

                st.divider()
                st.subheader("Grading Summary")

                if "CONNECT FEEDBACK:" in output:
                    breakdown, feedback = output.split("CONNECT FEEDBACK:", 1)
                    st.markdown(breakdown.strip())
                    st.subheader("Feedback for McGraw-Hill Connect")
                    st.text_area(
                        "Click the copy icon in the top right corner:",
                        value=feedback.strip(),
                        height=140
                    )
                else:
                    st.markdown(output)

            except Exception as e:
                st.error(f"Error calling model: {e}")
